import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./component/Navbar";
import Discountsofa from "./component/Discountsofa";
import Uniquesofa from "./component/Uniquesofa";
import Shopex from "./component/shopex";
import Product from "./component/Product";
import Hero from "./component/Hero";
import Fashon from "./component/Fashon";
import Footer from "./component/Footer";
import Form from "./component/Form";
import Information from "./component/Information";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-[100dvh] flex-col`}
      >
        <div>
          <Navbar/>
          <Hero/>
          <Information/>
          <Form/>
          <Fashon/>
          <Product/>

          <Shopex/>

          <Discountsofa/>
          <Uniquesofa/>
         
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}

